#!/bin/sh
# gChWall - Change GNOME Wallpaper
# Originally written in 2009 for GNOME,
# but supports all other wallpaper setting programs.
# 
# Copyright (C) 2009,2014 Malte Bublitz
#

GCHWALL_WAIT_TIME="5m"

set_wallpaper() {
	hsetroot -full $1
}

if [ $1 = "-h" ]
then
	echo 'gChWall 0.1
Copyright (C) 2009,2014 Malte Bublitz

--
Wallpaper list is stored in ~/.gchwallrc'
	exit 0
fi

if [ "$1" = "-d" ]
then
	while :
	do
		for wall in `cat ~/.gchwallrc`
		do
			hsetroot -full "$wall"
			sleep $GCHWALL_WAIT_TIME
		done
	done
else
	echo '_Only_ Accepted Command Line Options: -d - start daemon'
fi
