#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Password generator
#    Generates a random password. Length is passed as an argument, default is 8.
# 
# Copyright (c) 2013 Malte Bublitz.
# All rights reserved.
# 
# Licensed under the terms of the 2-clause BSD license.
# See LICENSE for details.
#

import random
import sys

def get_random_word(wordLen):
	allowed_chars  = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
	allowed_chars += 'abcdefghijklmnopqrstuvwxyz'
	allowed_chars += '0123456789'
	allowed_chars += '.,-_!?()/='
	word = ''
	for i in range(wordLen):
		word += random.choice(allowed_chars)
	return word

def main():
	if len(sys.argv)==2:
		count = int(sys.argv[1])
	else:
		count = 8
	print(get_random_word(count))

if __name__=="__main__":
	main()
