#!/bin/sh
#
# Get the IPv4 address of a DNS name.
#

AHOSTSV4=$(getent ahostsv4 $1)
[ $? -eq 2 ] && {
	echo "DNS name $1 could not be resolved." >&2
	exit 1
}
echo $AHOSTSV4 | head -n1 | awk '{ print $1 }'

