#!/usr/bin/env zsh
#
# git info
#    Shows information about a git repository
#    for the zsh prompt.
#

[ ! -d $HOME/.cache/git-info ] && mkdir -p $HOME/.cache/git-info
if ! git rev-parse --git-dir &>/dev/null; then
	UPSTREAM="no git"
else
	# Test internet connection, needed for the git remote command.
	# Using google-public-dns-a.google.com (8.8.8.8), which can be used for this.
	ping -c1 -W 1 8.8.8.8 &>/dev/null
	if [ $? -eq 1 ]; then
		UPSTREAM="!fail!"
	else
		CACHEFILE=~/.cache/git-info/`pwd | tr '/' '='`
		if [ -f $CACHEFILE ] && [[ $(python2 -c 'import os.path,time;print "yes" if (time.time()-os.path.getmtime("'"$CACHEFILE"'"))/(60*60*24) > 2.0 else "no"') == "no" ]]; then
			UPSTREAM=`cat $CACHEFILE`
		else
			REMOTE=`git config --get remote.origin.url`
			if [ -z "$REMOTE" ]; then
				REMOTE="(local)$(basename `pwd`)"
			fi
			BRANCH="$(git rev-parse --abbrev-ref HEAD)"
			if [[ "${REMOTE:0:14}" == "git@github.com" ]]; then
				UPSTREAM="${REMOTE:15:-4}:$BRANCH"
			elif [[ "${REMOTE:0:19}" == "https://github.com/" ]]; then
				UPSTREAM="${REMOTE:19}:$BRANCH"
			elif [[ "${REMOTE:0:24}" == "malte70@khaos.malte70.de" ]]; then
				UPSTREAM="khaos/${REMOTE:34:-4}:$BRANCH"
			elif [[ "${REMOTE:0:36}" == "git+ssh://khaos.malte70.de:/srv/git/" ]]; then
				UPSTREAM="khaos/${REMOTE:36:-4}:$BRANCH"
			elif [[ "${REMOTE:0:16}" == "git@repos.dma.do" ]]; then
				UPSTREAM="dma.do/${REMOTE:17:-4}:$BRANCH"
			else
				UPSTREAM="${REMOTE}:$BRANCH"
			fi
		fi
		echo -n $UPSTREAM > $CACHEFILE
	fi
	# number of uncommited changes
	# do not cache this.
	CHANGES=`git status -s | wc -l | stripwhite`
	if [ $CHANGES -gt 0 ]
	then
		UPSTREAM="${UPSTREAM}:${CHANGES}"
	fi
fi
echo $UPSTREAM
