#!/bin/bash

echo -e -n "Name of the protected area?\n> "
read AUTH_NAME
echo -e -n "Path to htpasswd file?\n> "
read AUTH_PATH

echo -e -n "User name? (can be empty)\n> "
read USER_NAME
echo -e -n "Password?\n> "
stty -echo
read USER_PASSWORD
stty echo

cat <<EOF



## .htaccess

AuthName "$AUTH_NAME"
AuthType Basic
AuthUserFile $AUTH_PATH/.htpasswd
require valid-user

## .htpasswd
EOF

htpasswd -n -B -b "$USER_NAME" "$USER_PASSWORD"
echo
echo
