#!/bin/sh
#
# lsjar
#    list all classes in a jar file
#

if [ $1 == "--help" ]
then
	cat <<EOF
lsjar: Lists the classes in a Java jar file.
Usage: lsjar [-c] <jarfile>
Options:
	--help
		Display this help text
	--version
		Display version information
	-v
		Enable verbose output, a.k.a. mark the Main class

EOF
	exit 0
fi

if [ $1 == "--version" ]
then
	echo "lsjar 0.20140207 (https://github.com/malte70/scripts"
	echo "Copyright (c) 2014 Malte Bublitz, https://malte-bublitz.de"
	echo "All rights reserved."
	exit 0
fi

if [ $1 == "-v" ]
then
	VERBOSE="y"
	shift
else
	VERBOSE="n"
fi

for jarfile in $@
do
	MAINCLASS=`unzip -q -c $jarfile META-INF/MANIFEST.MF | grep Main-Class | cut -d" " -f2`
	if [ $# -gt 1 ]
	then
		jarfile_nice=`basename $jarfile`
		jar tf $jarfile | grep -E '*.class' | sed "s/.class//g;s@/@.@g;s/^/${jarfile_nice}/g"
	else
		jar tf $jarfile | grep -E '*.class' | sed "s/.class//g;s@/@.@g"
	fi | {
		if [ $VERBOSE == "y" ]
		then
			sed "s/^/   /g;s/   $MAINCLASS/ * $MAINCLASS/g"
		else
			cat
		fi
		}
done
