#!/usr/bin/env bash
#
# md2html
#     Part of: malte70/scripts
#
# Markdown to HTML converter powered by pandoc
#

SCRIPT_NAME="$(basename $0)"
SCRIPT_VERSION="0.20230118"

source $(dirname $0)/_base.inc.sh

usage() {
	echo "Usage:"
	echo "  $SCRIPT_NAME"
	echo "  $SCRIPT_NAME [--version|--help]"
	echo "  $SCRIPT_NAME <filename.md>"
	echo
	echo "Options:"
	echo "  --version -V  Show the version and exit"
	echo "  --help    -h  Show this help and exit"
	echo
}

if [[ "$1" == "--help" || "$1" == "-h" ]]; then
	version
	usage
	exit 0
fi

if which pandoc &>/dev/null; then
	true
else
	echo "${SCRIPT_NAME}: Error: pandoc not found in \$PATH. Please install it."
	exit 1
fi

if [[ $1 == "-v" ]]; then
	VERBOSE=1
	shift
else
	VERBOSE=0
fi

_md2html() {
	markdown="$1"
	markdown_filename=$(basename "${markdown}")
	html="$2"
	title=$(grep '^# ' "$markdown" | head -n1 | cut -c3-)
	[[ -z $title ]] && title="${markdown_filename}"
	
	pandoc \
		--from gfm \
		--to html5 \
		--standalone \
		--metadata title="$title" \
		--include-in-header ~/.local/share/pandoc/templates/html5-style.inc.html \
		"$markdown" \
		--output "$html"
	
	# Table borders and cellpadding, the dirty way
	sed -i 's|<table>|<table border="1" cellpadding="6">|g' "$html"
}

markdown="$1"

if [[ ! -f "$markdown" ]]
then
	message_error "No such file or directory: $markdown"
	exit 13
fi

html="${markdown%.*}.html"

if [[ $VERBOSE -eq 1 ]]; then
	echo "$markdown -> $html"
fi

_md2html "$markdown" "$html"

