#!/usr/bin/env python
# -*- coding: utf-8 -*-

__doc__ = """ mFingerd

Copyright (c) 2012,2013 Malte Bublitz
All rights reserved.

Configuration is done in the CONFIG variable.
Set CONFIG.ServerInfo to the server information that
should be returned to the user if no username was
specified.
CONFIG.UserInfo contains the information for the users
that can be queried.
CONFIG.UserNonExistentError is returned if a user was
specified, but not listed in CONFIG.UserInfo.
"""

CONFIG = {
	"ServerInfo": "This is host.example.com.",
	"UserInfo": {
		"malte70": """Full name: Malte Bublitz
Twitter: @malte70
IRC: malte70 on irc.malte-bublitz.de"""
		},
        "UserNonExistentError": "The requested user does not exist."
	}

import SocketServer
import string

class FingerHandler(SocketServer.StreamRequestHandler):
	def handle(self):
		# read a line (limited to 512 byte to
		# avoid megabytes of data to process
		username = self.rfile.readline(512)
		
		# strip the username string
		username = string.strip(username)
		
		global CONFIG
		# send the requested username.
		if username=='':
			info = CONFIG["ServerInfo"]
		else:
			if CONFIG["UserInfo"].has_key(username):
				info = CONFIG["UserInfo"][username]
                        else:
				info = CONFIG["UserNonExistentError"]
		self.wfile.write(info+"\n")
		
if __name__=='__main__':
	# Create an server instance
	server = SocketServer.TCPServer( ('', 79), FingerHandler)
	
	# run the server
	try:
		server.serve_forever()
	except KeyboardInterrupt:
		print "\nCtr+C pressed.\nAborting..."
		server.shutdown()

