#!/bin/bash
#
# mips-run
#    run a MIPS assembler program like a shell script.
#    parses file with pypp, and executes it with mars.
#    Also strips out MARS version info from output.
# 
# Copyright (c) 2013 Malte Bublitz.
# All rights reserved.
# 
# Licensed under the terms of the 2-clause BSD license.
# See LICENSE for details.
#

MARS_JARFILE="/opt/mars/Mars.jar"
TMPFILE=/tmp/mips-run.$$

pypp <$1 >$TMPFILE

MARS_VERSION_INFO=$(java -jar $MARS_JARFILE h | head -n1 | awk '{ print $1 " " $2 }' | sed 's/\./\\./g')
java -jar $MARS_JARFILE sm $TMPFILE | sed -nr "/^$MARS_VERSION_INFO/!p"

rm $TMPFILE
