#!/bin/bash
#
# Show current IP
#
# Copyright (c) 2013 Malte Bublitz
# All rights reserved.
#

IPv4=$(ip addr show | grep inet\  |awk '{ print $2 }'  | cut -d/ -f1)
IPv6=$(ip addr show | grep inet6\  |awk '{ print $2 }' | cut -d/ -f1)
{
for IP in $IPv4
do
	echo $IP
done
} | sort
{
for IP in $IPv6
do
	echo $IP
done
} | sort
if which finger &>/dev/null
then
	finger ip@ip.malte-bublitz.de | tail -n+2
else
	curl http://ip.malte-bublitz.de; echo
fi
