#!/usr/bin/env python3
"""push: Send a notification to me using Pushover.

Example config file (~/.config/pushover-notify.toml):

[pushover]
appname  = "Gallifrey"
api_key  = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
user_key = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

"""

import sys
import os
import platform
import toml
import pushover


APP_NAME = "pushover-notify"
APP_VERSION = "0.2"
APP_UNIXNAME = APP_NAME.replace("-", "")
APP_CONFIG = os.path.expanduser("~/.config/pushover-notify.toml")


def pushover_send(api_key: str, user_key: str, message: str, title: str = ""):
	# print(f"""Current config:
	# 	api_key  = '{api_key}'
	# 	user_key = '{user_key}'
	# 	message  = '{message}'
	# 	title    = '{title}'
	# """)
	# 	return False

	po = pushover.Pushover(api_key)
	po.user(user_key)

	msg = po.msg(message)
	if len(title) > 0:
		msg.set("title", title)
	else:
		msg.set("title", platform.node())

	return po.send(msg)


def main():
	config = toml.load(APP_CONFIG)
	api_key = config.get("pushover").get("api_key")
	user_key = config.get("pushover").get("user_key")

	if len(sys.argv) > 1:
		title = sys.argv[1]
		message = " ".join(sys.argv[2:])

	else:
		title = ""
		if len(sys.argv):
			message = sys.argv[1]
		else:
			if sys.stdin.isatty():
				print("Please enter a message to be sent:", file=sys.stderr)
			message = sys.stdin.read()

	if not pushover_send(api_key, user_key, message, title):
		print("[{APP_NAME}] Error in pushover_send()", file=sys.stderr)
		return 1

	return 0


if __name__ == "__main__":
	if "--help" in sys.argv or "-h" in sys.argv:
		print("Usage:")
		print(f"\t{APP_NAME} [--help|-h|--version|-V]")
		print(f"\t*command* | {APP_NAME} [*title*]")
		sys.exit(0)

	elif "--version" in sys.argv or "-V" in sys.argv:
		print(f"{APP_NAME} v{APP_VERSION}")
		sys.exit(0)

	sys.exit(main())
