#!/usr/bin/env python2
# -*- coding: utf-8 -*-
#

import sys

import socket

# this is a calculator, so this might be needed.
from math import *

def c2re(z):
	return "r="+str(sqrt(z.real*z.real + z.imag * z.imag)) + "; e="+str(atan(z.imag / z.real))

sys.stdout.write("[H[2J]0;pycalc (malte70@"+socket.gethostname()+")")
cmd = ""
lastresult = 0
try:
	try:
		while True:
			print "(pycalc)%",
			cmd = raw_input()
			#cmd = cmd.replace("#", lastresult)
			if cmd.startswith("*"): cmd = "print "+cmd[1:]
			if not cmd in ["quit", "exit", ""]:
				if cmd == "clear":
					sys.stdout.write("[H[2J")
                                else:
					exec(cmd)
			if cmd in ["quit", "exit"]:
				break
	except KeyboardInterrupt:
		print ""
		sys.exit(0)
except EOFError:
	print ""
	sys.exit(0)
