#!/usr/bin/env python
#
# pypp
#    Minimal Python-based preprocessor
#
# Copyright (c) 2013 Malte Bublitz.
# All rights reserved.
# 
# Licensed under the terms of the 2-clause BSD license.
# See LICENSE for details.
#
# Usage
# -----
# define a macro with:
# 
#    #define	macroname	value
#
# Note that you need to use tabs as separators.
# multiline macros can be defined by using a backslash at
# the end of the line, like in C preprocessors.
# 

import sys

def main():
	_in = sys.stdin.read()
	macros = {}
	for line in _in.replace("\\\n", "%newline%").split("\n"):
		if line.startswith("#pypp:define"):
			_null, _name, _value = line.split("\t")
			macros[_name] = _value.replace("%newline%", "\n")
	for line in _in.replace("\\\n", "%newline%").split("\n"):
		if line.startswith("#pypp:define"):
			continue
		#print(macros)
		for m in macros:
			print(line.replace(m, macros[m]).replace("%newline%", "\n"))

if __name__=="__main__":
	main()
	
	

