#!/usr/bin/env python2
# -*- coding: utf-8 -*-
#

import sys

cmd = ""
try:
	try:
		while True:
			print "(pysh)%",
			cmd = raw_input()
			if not cmd in ["quit", "exit"]:
				if cmd == "clear":
					sys.stdout.write("[H[2J")
                                else:
					exec(cmd)
			if cmd in ["quit", "exit"]:
				break
	except KeyboardInterrupt:
		print ""
		sys.exit(0)
except EOFError:
	print ""
	sys.exit(0)
