#!/usr/bin/env python2
# -*- coding: utf-8 -*-
#
# QRCode generator
#    Generates a QR code as an PNG or JPEG image.
#
# Copyright (c) 2013 Malte Bublitz.
# All rights reserved.
#
# Licensed under the terms of the 2-clause BSD license.
# See LICENSE for details.
#

import sys
try:
	import qrcode
except ImportError:
	print "Please install python-qrcode."
	print "Get it at https://github.com/lincolnloop/python-qrcode"
	sys.exit(1)

def main():
	if len(sys.argv)!=3:
		print "Usage: qrcode <Filename> <Text>"
		sys.exit(1)

	filename = sys.argv[1]
	text     = sys.argv[2]

	qrcode.make(text).save(filename)

if __name__=="__main__":
	main()
