#!/bin/bash
#
# Play radio
# 
# SPDX-License-Identifier: WTFPL
#

if ! which mpg123 &>/dev/null; then
	echo "Error: mpg123 needed." >&2
	exit 1
fi

while :
 do
	clear
	echo "<~-- Radio --~>"
	echo
	echo "1: Morow"
	echo "2: HardBase.FM"
	echo "3: HARDRADIO"
	echo "4: EBM Radio"
	echo "q: quit"
	echo
	echo -n "? "
	read choice
	case "$choice" in
		1) mpg123 "http://stream.morow.com:9090"
		   ;;
		2) mpg123 "http://listen.hardbase.fm/tunein-mp3-pls"
			;;
		3) mpg123 "http://listen.hardradio.de/stream"
			;;
		4) mpg123 "http://www.ebm-radio.org:7000/"
			;;
		q) exit 0
		   ;;
	esac
done
