#!/usr/bin/env python
# -*- coding: utf-8 -*-

import urllib.request
import json

class User(object):
	data = {
		"gender": "",
		"name": "",
		"email": "",
		"username": "",
		"password": ""
	}
	
	def __init__(self, **kwargs):
		for key in kwargs:
			self.data[key] = kwargs[key]

	def getGender(self):
		return self.data["gender"]
		
	def getName(self):
		return self.data["name"]
		
	def getEmail(self):
		return self.data["email"]
		
	def getUsername(self):
		return self.data["username"]
		
	def getPassword(self):
		return self.data["password"]
	
		
def ucfirst(string):
	return string[0].upper() + string[1:]
	
def run():
	response = urllib.request.urlopen("http://api.randomuser.me/")
	json_string = response.read().decode("utf-8")
	parsed_json = json.loads(json_string)
	user = User(
			gender = parsed_json["results"][0]["user"]["gender"],
			name = ucfirst(parsed_json["results"][0]["user"]["name"]["first"])+" "+ucfirst(parsed_json["results"][0]["user"]["name"]["last"]),
			email = parsed_json["results"][0]["user"]["email"],
			username = parsed_json["results"][0]["user"]["username"],
			password = parsed_json["results"][0]["user"]["password"],
		)
	print("Name........: "+user.getName())
	print("Gender......: "+user.getGender())
	print("Email.......: "+user.getEmail())
	print("Username....: "+user.getUsername())
	print("Password....: "+user.getPassword())

if __name__ == "__main__":
	run()
