#!/bin/zsh
#
# Screenshot tool
#

WAIT_TIME=5
DO_EDIT=yes
IMAGE_EDITOR=`which gimp` || IMAGE_EDITOR=`which xdg-open`
TARGETDIR="khaos.mcbx.de:~/f.malte70.de"

IMGNAME="screenshot_`hostname -s`_`date --iso-8601`_$(generate_password 8).png"
IMGPATH="$(xdg-user-dir PICTURES)/$IMGNAME"

do_screenshot() {
	scrot $IMGPATH
}

echo "Waiting 5 seconds..."
sleep 5s
do_screenshot
echo "File is $IMGPATH."
if [[ $DO_EDIT == "yes" ]]
then
	echo -n "Press enter to edit your picture.\n> "
	read
	$IMAGE_EDITOR $IMGPATH
else
	echo -n "Press enter to continue uploading, or Ctrl+C to abort.\n> "
	read
fi
echo -n "Uploading via scp..."

scp -q $IMGPATH "${TARGETDIR}/${IMGNAME}"
echo "done."

echo "Uploaded to: http://f.malte70.de/$IMGNAME"
