#!/bin/zsh
#
# Screenshot tool
#

IMGNAME="screenshot.`hostname -s`_`date --iso-8601`.png"
IMGPATH="$HOME/Bilder/$IMGNAME"

scrot $IMGPATH

echo "File is $IMGPATH."
echo "Press enter to continue after you edited it, or Ctrl+C to abort upload"
read

scp -q $IMGPATH khaos.malte70.de:~/f.malte70.de/$IMGNAME

echo "Uploaded to: http://f.malte70.de/$IMGNAME"
