#!/bin/sh
# startup script for uzbl

# check if uzbl-tabbed is installed (it is in an extra package that might not be installed in Arch Linux)
if which uzbl-tabbed &>/dev/null
then
	UZBL=`which uzbl-tabbed`
else
	if which uzbl-browser &>/dev/null
	then
		UZBL=`which uzbl-browser`
	else
		echo "Uzbl doesn't seem to be installed, or it is not in the PATH." >&2
		exit 1
	fi
fi

exec $UZBL $@
