#!/usr/bin/env python2
# -*- coding: utf-8 -*-
#
# Website screenshot generator
#
# Copyright (c) 2013 Malte Bublitz.
# All rights reserved.
#
# Licensed under the terms of the 2-clause BSD license.
# See LICENSE for details.
#

import sys
try:
	from pyvirtualdisplay import Display
except ImportError:
	print "Please install python-pyvirtualdisplay."
	print "Get it at https://pypi.python.org/pypi/PyVirtualDisplay"
	sys.exit(1)
try:
	from selenium import webdriver
except ImportError:
	print "Please install python2-selenium."
	print "Get it at http://pypi.python.org/pypi/selenium"
	sys.exit(1)

def main():
	verbose = False
	if sys.argv[1]=="-v" or sys.argv[1]=="--version":
		del sys.argv[1]
		verbose=True

	if verbose:print "Setting up display (size 1280x1024)...",
	display = Display(visible=0, size=(1280, 1024))
	if verbose:print "done."

	if verbose:print "Starting display...",
	display.start()
	if verbose:print "done."

	if verbose:print "Starting Browser...",
	browser = webdriver.Firefox()
	if verbose:print "done."

	if verbose:print "Getting web page...",
	browser.get(sys.argv[1])
	if verbose:print "done."

	if verbose:print "Saving Screenshot...",
	browser.save_screenshot(sys.argv[2])
	if verbose:print "done."

	if verbose:print "Cleaning up...",
	browser.quit()
	display.stop()
	if verbose:print "done."

if __name__=="__main__":
	main()
